services:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dev -h postgres || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-collect-metrics:
    image: api-collect-metrics
    ports:
      - "5002:80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:80
      ASPNETCORE_ENVIRONMENT: Production
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: dev
      DB_HOST: postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-recommendations:
    image: api-recommendations
    ports:
      - "5003:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:80
      ASPNETCORE_ENVIRONMENT: Production
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: dev
      DB_HOST: postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-ai:
    image: api-ai
