name: Backup DB

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # Exécution tous les jours à 2h du matin

env:
  ASPNETCORE_ENVIRONMENT: production
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
  LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
  GF_SECURITY_ADMIN_USER: ${{ secrets.GF_SECURITY_ADMIN_USER }}
  GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
  SIMULATOR_1_ID: ${{ secrets.SIMULATOR_1_ID }}
  SIMULATOR_2_ID: ${{ secrets.SIMULATOR_2_ID }}
  SIMULATOR_3_ID: ${{ secrets.SIMULATOR_3_ID }}

jobs:
  backup:
    name: Backup PostgreSQL on VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Init : Création du dossier des backups
      - name: Créer dossier local pour backup
        run: mkdir -p ./backups

      # Étape 1 : Backup sur le VPS via SSH
      - name: Backup via SSH
        uses: appleboy/ssh-action@v0.1.6
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/deploy/GreenAIT
            export ASPNETCORE_ENVIRONMENT=${{ env.ASPNETCORE_ENVIRONMENT }}
            export POSTGRES_USER=${{ env.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}
            export POSTGRES_DB=${{ env.POSTGRES_DB }}
            export REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
            export LETSENCRYPT_EMAIL=${{ env.LETSENCRYPT_EMAIL }}
            export GF_SECURITY_ADMIN_USER=${{ env.GF_SECURITY_ADMIN_USER }}
            export GF_SECURITY_ADMIN_PASSWORD=${{ env.GF_SECURITY_ADMIN_PASSWORD }}
            export SIMULATOR_1_ID=${{ env.SIMULATOR_1_ID }}
            export SIMULATOR_2_ID=${{ env.SIMULATOR_2_ID }}
            export SIMULATOR_3_ID=${{ env.SIMULATOR_3_ID }}
            ./scripts/backup_db.sh

      # Etape 2 : Copie de la backup
      - name: Download backup from VPS
        run: |
          ls
          scp -i ${{ secrets.VPS_SSH_KEY }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/deploy/GreenAIT/backups/latest.sql.gz ./latest.sql.gz

      # Étape 3 : Upload vers GitHub Actions
      - name: Upload backup to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: greenai-db-backup
          path: ./backups/latest.sql.gz
          retention-days: 7
